export const CONTACT_SEND_MAIL_REQUEST = 'CONTACT_SEND_MAIL_REQUEST'
export const CONTACT_SEND_MAIL_SUCCESS = 'CONTACT_SEND_MAIL_SUCCESS'
export const CONTACT_SEND_MAIL_FAIL = 'CONTACT_SEND_MAIL_FAIL'
export const CONTACT_SEND_MAIL_RESET = 'CONTACT_SEND_MAIL_RESET'
