export const SERVER_STATS_REQUEST = 'SERVER_STATS_REQUEST'
export const SERVER_STATS_SUCCESS = 'SERVER_STATS_SUCCESS'
export const SERVER_STATS_FAIL = 'SERVER_STATS_FAIL'

export const SERVER_SET_VISIT_COUNT_REQUEST = 'SERVER_SET_VISIT_COUNT_REQUEST'
export const SERVER_SET_VISIT_COUNT_SUCCESS = 'SERVER_SET_VISIT_COUNT_SUCCESS'
export const SERVER_SET_VISIT_COUNT_FAIL = 'SERVER_SET_VISIT_COUNT_FAIL'

export const SERVER_SET_EMAIL_COUNT_REQUEST = 'SERVER_SET_EMAIL_COUNT_REQUEST'
export const SERVER_SET_EMAIL_COUNT_SUCCESS = 'SERVER_SET_EMAIL_COUNT_SUCCESS'
export const SERVER_SET_EMAIL_COUNT_FAIL = 'SERVER_SET_EMAIL_COUNT_FAIL'

export const SERVER_SET_EMAIL_TIME_REQUEST = 'SERVER_SET_EMAIL_TIME_REQUEST'
export const SERVER_SET_EMAIL_TIME_SUCCESS = 'SERVER_SET_EMAIL_TIME_SUCCESS'
export const SERVER_SET_EMAIL_TIME_FAIL = 'SERVER_SET_EMAIL_TIME_FAIL'
export const SERVER_SET_EMAIL_TIME_RESET = 'SERVER_SET_EMAIL_TIME_RESET'
